apiVersion: apps/v1
kind: Deployment
metadata:
  name: versitygw
  labels:
    app: versitygw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: versitygw
  template:
    metadata:
      labels:
        app: versitygw
    spec:
      containers:
      - name: versitygw
        image: versity/versitygw:latest
        args:
        - posix
        - /data
        env:
        - name: ROOT_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: ROOT_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        ports:
        - containerPort: 7070
          name: s3
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: versitygw-data
